### ISSUE TITLE
Cachet support

### ISSUE THREAD

**Issue by m1guelpf** [LKDevelopment/laravel-uptime-monitor-api#3]
I would like to integrate this with Cachet.
What do I have to do to only get current status?

**Comment by m1guelpf** [comment]
Cool!
Could you send me a link when it is finished?
(I would like to help, but I'm still learning and my Laravel knowledge is limited)

**Comment by LKDevelopment** [comment]
@m1guelpf I've made a basic and unstable implementation hear: https://github.com/LKDevelopment/laravel-uptime-monitor-cachet-integration

**Comment by LKDevelopment** [comment]
@m1guelpf The Package is released.
