### ISSUE TITLE
can you update this to support spatie's new version?

### ISSUE THREAD

**Issue by vesper8** [LKDevelopment/laravel-uptime-monitor-api#4]
Really loving the extra functionality you added with the api and the cachet integration. But right now your packages only work with spatie's laravel-uptime-monitor v1.02 and his latest version is up to 1.2.2

Any chance you could update your packages to allow his latest additions to be used as well?

many thanks!!

**Comment by LKDevelopment** [comment]
sure, i will update it in the next couple of days.

**Comment by LKDevelopment** [comment]
Okay, i did it. All Addon Packages support spaties uptime monitor new versions now :)
